services:
  db:
    image: postgres:16
    container_name: task_db
    restart: always
    environment:
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: task_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: task_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://task_user:1234@db:5432/task_db
    ports: 
      - "8000:8000"
    volumes:
      - .:/app
volumes:
  postgres_data: